-- Tagging schema for H2 (local profile and tests). Same tables and keys as the PostgreSQL migration,
-- minus partitioning and collation tuning.

CREATE TABLE tags (
    tenant_id   VARCHAR(64)  NOT NULL,
    tag_id      BIGINT       NOT NULL,
    name        VARCHAR(256) NOT NULL,
    name_norm   VARCHAR(256) NOT NULL,
    color       VARCHAR(16),
    version     BIGINT       NOT NULL,
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by  VARCHAR(128),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (tenant_id, tag_id)
);
CREATE UNIQUE INDEX ux_tags_name ON tags (tenant_id, name_norm);

CREATE TABLE entities (
    tenant_id   VARCHAR(64)  NOT NULL,
    entity_type VARCHAR(40)  NOT NULL,
    entity_id   VARCHAR(128) NOT NULL,
    entity_seq  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_entities PRIMARY KEY (tenant_id, entity_type, entity_id)
);
CREATE UNIQUE INDEX ux_entities_seq ON entities (tenant_id, entity_seq);

CREATE TABLE entity_tags (
    tenant_id   VARCHAR(64)  NOT NULL,
    entity_type VARCHAR(40)  NOT NULL,
    entity_id   VARCHAR(128) NOT NULL,
    tag_id      BIGINT       NOT NULL,
    entity_seq  BIGINT       NOT NULL,
    created_by  VARCHAR(128),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_entity_tags PRIMARY KEY (tenant_id, entity_type, entity_id, tag_id)
);
CREATE INDEX ix_entity_tags_by_tag ON entity_tags (tenant_id, tag_id, entity_seq);

CREATE TABLE tag_usage (
    tenant_id VARCHAR(64) NOT NULL,
    tag_id    BIGINT      NOT NULL,
    bucket    SMALLINT    NOT NULL,
    cnt       BIGINT      NOT NULL,
    CONSTRAINT pk_tag_usage PRIMARY KEY (tenant_id, tag_id, bucket)
);

CREATE TABLE outbox (
    seq        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  VARCHAR(64)    NOT NULL,
    event_type VARCHAR(32)    NOT NULL,
    payload    VARCHAR(65535) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE outbox_relay_state (
    id         INT    PRIMARY KEY,
    last_seq   BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
INSERT INTO outbox_relay_state (id, last_seq, updated_at) VALUES (1, 0, CURRENT_TIMESTAMP);

CREATE TABLE idempotency_keys (
    tenant_id    VARCHAR(64)    NOT NULL,
    idem_key     VARCHAR(128)   NOT NULL,
    request_hash VARCHAR(64)    NOT NULL,
    response     VARCHAR(65535) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_idempotency_keys PRIMARY KEY (tenant_id, idem_key)
);
CREATE INDEX ix_idempotency_created ON idempotency_keys (created_at);
