-- Tagging schema for PostgreSQL 14+ (vanilla, RDS, Cloud SQL, CloudNativePG; Citus with tenant_id as
-- the distribution column). It uses only community PostgreSQL features, so it moves unchanged
-- between clouds.
--
-- * tenant_id leads every key: a tenant's rows are contiguous, and the table can be distributed by tenant.
-- * COLLATE "C" on keys: byte-order comparison, the same in every locale, and LIKE 'prefix%' can use the index.
-- * entity_tags is hash-partitioned by tenant (16 partitions) so vacuum and index maintenance stay small per partition.

CREATE TABLE tags (
    tenant_id   VARCHAR(64)  COLLATE "C" NOT NULL,
    tag_id      BIGINT       NOT NULL,
    name        VARCHAR(256) NOT NULL,
    name_norm   VARCHAR(256) COLLATE "C" NOT NULL,
    color       VARCHAR(16),
    version     BIGINT       NOT NULL,
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by  VARCHAR(128),
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (tenant_id, tag_id)
) WITH (fillfactor = 90);
CREATE UNIQUE INDEX ux_tags_name ON tags (tenant_id, name_norm);

CREATE TABLE entities (
    tenant_id   VARCHAR(64)  COLLATE "C" NOT NULL,
    entity_type VARCHAR(40)  COLLATE "C" NOT NULL,
    entity_id   VARCHAR(128) COLLATE "C" NOT NULL,
    entity_seq  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_entities PRIMARY KEY (tenant_id, entity_type, entity_id)
);
CREATE UNIQUE INDEX ux_entities_seq ON entities (tenant_id, entity_seq);

CREATE TABLE entity_tags (
    tenant_id   VARCHAR(64)  COLLATE "C" NOT NULL,
    entity_type VARCHAR(40)  COLLATE "C" NOT NULL,
    entity_id   VARCHAR(128) COLLATE "C" NOT NULL,
    tag_id      BIGINT       NOT NULL,
    entity_seq  BIGINT       NOT NULL,
    created_by  VARCHAR(128),
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_entity_tags PRIMARY KEY (tenant_id, entity_type, entity_id, tag_id)
) PARTITION BY HASH (tenant_id);

DO $$
BEGIN
    FOR i IN 0..15 LOOP
        EXECUTE format('CREATE TABLE entity_tags_p%s PARTITION OF entity_tags FOR VALUES WITH (MODULUS 16, REMAINDER %s)', i, i);
    END LOOP;
END $$;

-- The inverted index: tag -> entities, in entitySeq order (keyset pagination, no sort).
CREATE INDEX ix_entity_tags_by_tag ON entity_tags (tenant_id, tag_id, entity_seq);

-- Sharded counters: an attach increments a random one of N buckets, so a hot tag isn't one hot row.
CREATE TABLE tag_usage (
    tenant_id VARCHAR(64) COLLATE "C" NOT NULL,
    tag_id    BIGINT      NOT NULL,
    bucket    SMALLINT    NOT NULL,
    cnt       BIGINT      NOT NULL,
    CONSTRAINT pk_tag_usage PRIMARY KEY (tenant_id, tag_id, bucket)
) WITH (fillfactor = 70);

CREATE TABLE outbox (
    seq        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  VARCHAR(64) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    payload    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE outbox_relay_state (
    id         INT         PRIMARY KEY,
    last_seq   BIGINT      NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
INSERT INTO outbox_relay_state (id, last_seq, updated_at) VALUES (1, 0, now());

CREATE TABLE idempotency_keys (
    tenant_id    VARCHAR(64)  COLLATE "C" NOT NULL,
    idem_key     VARCHAR(128) COLLATE "C" NOT NULL,
    request_hash VARCHAR(64)  NOT NULL,
    response     TEXT         NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_idempotency_keys PRIMARY KEY (tenant_id, idem_key)
);
CREATE INDEX ix_idempotency_created ON idempotency_keys (created_at);
